apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  labels:
    run: grafana-server
spec:
  ports:
  - port: 3000
    nodePort: 30043
    protocol: TCP
  selector:
    run: grafana-server
  type: NodePort
