---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "nats.name" . }}
  labels:
    app: {{ template "nats.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  selector:
    app: {{ template "nats.name" . }}
  ports:
  - name: client
    port: 4222
    nodePort: 30041
    protocol: TCP
  type: NodePort