{
 "title": "New dashboard Copy",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(gateway_function_invocation_total[1m])"
    }
   ]
  },
  {
   "title": "img-classifier-hub",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gateway_service_count{function_name='img-classifier-hub.openfaas-fn'}"
    }
   ]
  },
  {
   "title": "Sentiment",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gateway_service_count{function_name='sentiment.openfaas-fn'}"
    }
   ]
  },
  {
   "title": "Figlet",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gateway_service_count{function_name='figlet.openfaas-fn'}"
    }
   ]
  },
  {
   "title": "Firing",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ALERTS" }
   ]
  }
 ]
}